
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hprc-qc-annotation"
version = "0.1.0"
description = "HPRC Pangenome Quality Control - Annotation Module"
authors = [{name = "HPRC Maintenance and Improvement Working Group"}]
license = {text = "Apache-2.0"}
requires-python = ">=3.8"
dependencies = [
    "click>=8.0",
    "pandas>=1.5",
    "biopython>=1.78",
    # Add annotation-specific deps here
]